<?php $posts = Mage::registry('tickets_post'); ?>
<div class="dashboard">
    <div class="page-title">
        <h1><?php echo $this->__('Open new support ticket') ?></h1>
    </div>

    <form action="<?php echo $this->getUrl('*/*/new', array('_current' => true)); ?>" method="post" autocomplete="off" id="form-new-ticket">
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('New ticket') ?></h2>
            <ul class="form-list">
                <li class="wide">
                    <label for="subject" class="required"><em>*</em><?php echo $this->__('Subject') ?></label>
                    <div class="input-box">
                        <input type="text" name="subject" title="<?php echo $this->__('Ticket subject') ?>" id="subject" class="input-text required-entry validation-passed">
                    </div>
                </li>
                <li class="wide">
                    <label for="message" class="required"><em>*</em><?php echo $this->__('Message') ?></label>
                    <div class="input-box">
                        <textarea name="message" id="message" class="input-text  required-entry validation-passed"></textarea>
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
                <button type="submit" title="<?php echo $this->__('Submit new support ticket') ?>" class="button validation-passed"><span><?php echo $this->__('Submit') ?></span></button>
            <p class="back-link"><a href="<?php echo $this->getUrl('support/tickets/', array('_current' => true)); ?>"><small>« </small><?php echo $this->__('Back') ?></a></p>
        </div>
    </form>
    <script type="text/javascript">var customForm = new VarienForm('form-new-ticket');</script>
</div>